[package]
name = "diri"
version = "0.1.0"
edition = "2021"
description = """
Diri is a library / binary related to the
indexation of Solis data (orderbook smart contracts).
"""

[dependencies]
futures = "0.3.28"
mongodb = "2.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# TODO: add more stuff to the workspace after merge.
url = "2.3.1"
clap = { version = "4.3.19", features = ["derive", "env", "string"] }
regex = "1.9.1"
env_logger = "0.10.0"
log = "0.4.17"
dotenv = "0.15.0"
thiserror = "1.0.32"

anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
starknet.workspace = true
ark-starknet.workspace = true
