[package]
name = "arkchain"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.11.0" }

[[target.starknet-contract]]
sierra = true
casm = true
